// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphjUfCDSg9EYK4tjKKZbSlnaw6CUf3tE',
    appId: '1:893679215534:web:16f2dfe63a6d81b39d1e3f',
    messagingSenderId: '893679215534',
    projectId: 'educonnect-fe617',
    authDomain: 'educonnect-fe617.firebaseapp.com',
    storageBucket: 'educonnect-fe617.firebasestorage.app',
    measurementId: 'G-VRYFR4VHG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ARSfa58Qtl6uGNF8JhNQM5-BIXlBWq8',
    appId: '1:893679215534:android:a6ea6dea988d0dea9d1e3f',
    messagingSenderId: '893679215534',
    projectId: 'educonnect-fe617',
    storageBucket: 'educonnect-fe617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVMT1F2UrPjECbuu7PSEIwgO1G921ZKQ',
    appId: '1:893679215534:ios:cf8e19bbdebd50619d1e3f',
    messagingSenderId: '893679215534',
    projectId: 'educonnect-fe617',
    storageBucket: 'educonnect-fe617.firebasestorage.app',
    iosClientId: '893679215534-7culrsjc4n7pqj151ucd27g36r76koss.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADVMT1F2UrPjECbuu7PSEIwgO1G921ZKQ',
    appId: '1:893679215534:ios:cf8e19bbdebd50619d1e3f',
    messagingSenderId: '893679215534',
    projectId: 'educonnect-fe617',
    storageBucket: 'educonnect-fe617.firebasestorage.app',
    iosClientId: '893679215534-7culrsjc4n7pqj151ucd27g36r76koss.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDphjUfCDSg9EYK4tjKKZbSlnaw6CUf3tE',
    appId: '1:893679215534:web:eb9bfc801dba46a59d1e3f',
    messagingSenderId: '893679215534',
    projectId: 'educonnect-fe617',
    authDomain: 'educonnect-fe617.firebaseapp.com',
    storageBucket: 'educonnect-fe617.firebasestorage.app',
    measurementId: 'G-DS7MNWEFSH',
  );
}
